version: '1'
services:
  otp:
    build: src/In.ProjectEKA.OtpService/.
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql:
  postgresql_data: