replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmniindiadistro
  name: otp-service
  tag: latest

service:
  type: ClusterIP
  port: 8092

config:
  WHITELISTED_NUMBERS: ""

autoscaling:
  enabled: false
