name: feature-branches

on:
  push:
    branches:
      - test-branch
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet core '7.0.100'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.100'
      - name: Build with dotnet
        run: dotnet build otp_service.sln
      - name: Run unit tests
        run: dotnet test otp_service.sln
